### ISSUE TITLE
Class 'AMQPConnection' not found

### ISSUE THREAD

**Issue by davidmpaz** [proophsoftware/event-machine-skeleton#20]
Hi,

thanks for this wonderfull guide. I head up with this exception while following it. 

I did check image used in docker-compose [prooph/php:7.2-fpm](https://github.com/prooph/docker-files/blob/master/php/7.2-fpm) and it seems that it should be installed, still when i go inside the container and try to check the extension with `php -i | grep amqp`  i get nothing.

Any idea on what is happening would be appreciated?

thanks in advance for your time,
David

**Comment by sandrokeil** [comment]
Thank you very much for your report. This is an issue of the [PHP prooph/docker-files](https://github.com/prooph/docker-files/issues/35) due missing config file for amqp. This is now fixed. Please pull the new Docker images.
